site_name: "MEDEA  documentation"
site_url: "https://medea.docs.rokubun.cat"
theme:
  name: material
  logo: 'https://www.rokubun.cat/assets/images/medea_logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'deep orange'
    accent: 'blue grey'
  custom_dir: 'custom'
  rokubun_url: 'https://www.rokubun.cat'
nav:
  - Home: 'index.md'
  - Quick start guide: 'quick_start_guide.md'
  - Flashing an image: 'flash_image_guide.md'
  - Troubleshooting: 'troubleshooting.md'
  - Medea in projects:
    - AMIC: 'projects/amic.md'
extra_css:
  - 'stylesheets/extra.css'
repo_name: 'rokubun/medea-docs'
repo_url: 'https://github.com/rokubun/medea-docs'

